/**
 * API tags constants for RTK Query cache invalidation
 */

// Master Data API Tags
export const API_TAG_OPERATIONS_TITLES = "Title" as const;
export const API_TAG_OPERATIONS_SERVICES = "Service" as const;
export const API_TAG_OPERATIONS_LANGUAGES = "Language" as const;
export const API_TAG_OPERATIONS_DEPARTMENTS = "Department" as const;

// User Profile API Tags
export const API_TAG_OPERATIONS_PROFILE = "Profile" as const;

// Employee API Tags
export const API_TAG_OPERATIONS_EMPLOYEES = "Employee" as const;
export const API_TAG_OPERATIONS_EMPLOYEE_STATS = "EmployeeStats" as const;

// Analysis Templates API Tags
export const API_TAG_OPERATIONS_ANALYSIS_TEMPLATES =
  "AnalysisTemplate" as const;

// Patient API Tags
export const API_TAG_OPERATIONS_PATIENTS = "Patient" as const;
export const API_TAG_OPERATIONS_PATIENT_STATS = "PatientStats" as const;

// Roles and Permissions API Tags
export const API_TAG_OPERATIONS_ROLES = "Role" as const;
export const API_TAG_OPERATIONS_PERMISSIONS = "Permission" as const;

// Location API Tags (New unified structure)
export const API_TAG_OPERATIONS_LOCATION = "Location" as const;

// Protocol Template API Tags
export const API_TAG_OPERATIONS_PROTOCOL_TEMPLATES =
  "ProtocolTemplate" as const;

// Medical Card API Tags
export const API_TAG_OPERATIONS_APPOINTMENTS = "Appointment" as const;
export const API_TAG_OPERATIONS_VISITS = "Visit" as const;
export const API_TAG_OPERATIONS_PRESCRIPTIONS = "Prescription" as const;
export const API_TAG_OPERATIONS_SERVICE_ORDERS = "ServiceOrder" as const;

// Patient Parameters and Allergies API Tags
export const API_TAG_OPERATIONS_PATIENT_PARAMETERS =
  "PatientParameter" as const;
export const API_TAG_OPERATIONS_PATIENT_ALLERGIES = "PatientAllergy" as const;
export const API_TAG_OPERATIONS_PARAMETER_DEFINITIONS =
  "ParameterDefinition" as const;

// Invoice API Tags
export const API_TAG_OPERATIONS_INVOICES = "Invoice" as const;

// Reception Dashboard API Tags
export const API_TAG_OPERATIONS_RECEPTION = "Reception" as const;

// File Management API Tags
export const API_TAG_OPERATIONS_FILES = "Files" as const;

// Statistics API Tags
export const API_TAG_OPERATIONS_STATS = "Stats" as const;

// Organization API Tags
export const API_TAG_OPERATIONS_ORGANIZATION = "Organization" as const;

// Appointment Type API Tags
export const API_TAG_OPERATIONS_APPOINTMENT_TYPES = "AppointmentType" as const;
export const API_TAG_OPERATIONS_APPOINTMENT_CANCEL_TYPES =
  "AppointmentCancelType" as const;

// Leave Type and Holiday API Tags
export const API_TAG_OPERATIONS_LEAVE_TYPES = "LeaveType" as const;
export const API_TAG_OPERATIONS_HOLIDAYS = "Holiday" as const;

// Employee Availability and Leave Days API Tags
export const API_TAG_OPERATIONS_EMPLOYEE_AVAILABILITY =
  "EmployeeAvailability" as const;
export const API_TAG_OPERATIONS_EMPLOYEE_LEAVE_DAYS =
  "EmployeeLeaveDays" as const;

export type ApiTagTypes =
  | typeof API_TAG_OPERATIONS_TITLES
  | typeof API_TAG_OPERATIONS_SERVICES
  | typeof API_TAG_OPERATIONS_LANGUAGES
  | typeof API_TAG_OPERATIONS_DEPARTMENTS
  | typeof API_TAG_OPERATIONS_PROFILE
  | typeof API_TAG_OPERATIONS_EMPLOYEES
  | typeof API_TAG_OPERATIONS_EMPLOYEE_STATS
  | typeof API_TAG_OPERATIONS_PATIENTS
  | typeof API_TAG_OPERATIONS_PATIENT_STATS
  | typeof API_TAG_OPERATIONS_ANALYSIS_TEMPLATES
  | typeof API_TAG_OPERATIONS_ROLES
  | typeof API_TAG_OPERATIONS_PERMISSIONS
  | typeof API_TAG_OPERATIONS_LOCATION
  | typeof API_TAG_OPERATIONS_PROTOCOL_TEMPLATES
  | typeof API_TAG_OPERATIONS_APPOINTMENTS
  | typeof API_TAG_OPERATIONS_VISITS
  | typeof API_TAG_OPERATIONS_PRESCRIPTIONS
  | typeof API_TAG_OPERATIONS_SERVICE_ORDERS
  | typeof API_TAG_OPERATIONS_PATIENT_PARAMETERS
  | typeof API_TAG_OPERATIONS_PATIENT_ALLERGIES
  | typeof API_TAG_OPERATIONS_PARAMETER_DEFINITIONS
  | typeof API_TAG_OPERATIONS_INVOICES
  | typeof API_TAG_OPERATIONS_RECEPTION
  | typeof API_TAG_OPERATIONS_FILES
  | typeof API_TAG_OPERATIONS_STATS
  | typeof API_TAG_OPERATIONS_ORGANIZATION
  | typeof API_TAG_OPERATIONS_APPOINTMENT_TYPES
  | typeof API_TAG_OPERATIONS_APPOINTMENT_CANCEL_TYPES
  | typeof API_TAG_OPERATIONS_LEAVE_TYPES
  | typeof API_TAG_OPERATIONS_HOLIDAYS
  | typeof API_TAG_OPERATIONS_EMPLOYEE_AVAILABILITY
  | typeof API_TAG_OPERATIONS_EMPLOYEE_LEAVE_DAYS;

// Unified API Tags object for easier access
export const API_TAGS = {
  TITLE: API_TAG_OPERATIONS_TITLES,
  SERVICE: API_TAG_OPERATIONS_SERVICES,
  LANGUAGE: API_TAG_OPERATIONS_LANGUAGES,
  DEPARTMENT: API_TAG_OPERATIONS_DEPARTMENTS,
  PROFILE: API_TAG_OPERATIONS_PROFILE,
  EMPLOYEE: API_TAG_OPERATIONS_EMPLOYEES,
  EMPLOYEE_STATS: API_TAG_OPERATIONS_EMPLOYEE_STATS,
  PATIENT: API_TAG_OPERATIONS_PATIENTS,
  PATIENT_STATS: API_TAG_OPERATIONS_PATIENT_STATS,
  ANALYSIS_TEMPLATE: API_TAG_OPERATIONS_ANALYSIS_TEMPLATES,
  ROLE: API_TAG_OPERATIONS_ROLES,
  PERMISSION: API_TAG_OPERATIONS_PERMISSIONS,
  LOCATION: API_TAG_OPERATIONS_LOCATION,
  PROTOCOL_TEMPLATE: API_TAG_OPERATIONS_PROTOCOL_TEMPLATES,
  APPOINTMENT: API_TAG_OPERATIONS_APPOINTMENTS,
  VISIT: API_TAG_OPERATIONS_VISITS,
  PRESCRIPTION: API_TAG_OPERATIONS_PRESCRIPTIONS,
  SERVICE_ORDER: API_TAG_OPERATIONS_SERVICE_ORDERS,
  PATIENT_PARAMETER: API_TAG_OPERATIONS_PATIENT_PARAMETERS,
  PATIENT_ALLERGY: API_TAG_OPERATIONS_PATIENT_ALLERGIES,
  PARAMETER_DEFINITION: API_TAG_OPERATIONS_PARAMETER_DEFINITIONS,
  INVOICE: API_TAG_OPERATIONS_INVOICES,
  RECEPTION: API_TAG_OPERATIONS_RECEPTION,
  FILES: API_TAG_OPERATIONS_FILES,
  STATS: API_TAG_OPERATIONS_STATS,
  ORGANIZATION: API_TAG_OPERATIONS_ORGANIZATION,
  APPOINTMENT_TYPE: API_TAG_OPERATIONS_APPOINTMENT_TYPES,
  APPOINTMENT_CANCEL_TYPE: API_TAG_OPERATIONS_APPOINTMENT_CANCEL_TYPES,
  LEAVE_TYPE: API_TAG_OPERATIONS_LEAVE_TYPES,
  HOLIDAY: API_TAG_OPERATIONS_HOLIDAYS,
} as const;
